FROM python:3.8

RUN mkdir multibot
WORKDIR ./multibot

COPY ./requirements.txt ./requirements.txt

RUN pip3 install --upgrade pip
RUN pip3 install bitmex
RUN pip3 install dydx_v3_python
RUN pip3 install python-dotenv
RUN pip3 install --no-cache-dir --user -r requirements.txt
RUN pip3 install --upgrade requests

ENV PYTHONPATH="/:$PYTHONPATH"
ENV TZ=Europe/London

COPY . .

RUN touch rates.txt

