version: '3.5'

services:

  balancing:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "Dockerfile.workers"
    env_file:
      - .env
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python tasks/periodic/balancing.py'

