version: '3.5'

services:

  balancing_eth:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.eth
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python tasks/periodic/balancing.py'

  balancing_btc:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.btc
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python tasks/periodic/balancing.py'

  get_orders_results_eth:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.eth
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event_${GLOBAL_SYMBOL}.get_orders_results'

  get_orders_results_btc:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.btc
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event_${GLOBAL_SYMBOL}.get_orders_results'

  balance_check:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.eth
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.check_balance'

  funding:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.eth
    restart: always
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.periodic.funding'

  producer:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfile.workers"
    env_file:
      - .env.eth
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python producer.py'